### ISSUE TITLE
Make module work under prove

### ISSUE THREAD

**Issue by nkh** [raku-community-modules/Terminal-Width#2]
From Test::Notice:
use Terminal::Width; # doesn't actually work under `prove`

It would be good if that was in the documentation of Term::Width.

I have used the code below which I believe works under prove
$.width //= %+((qx[stty size] || '0 80') ~~ /\d+ \s+ (\d+)/)[0] ;

**Comment by JJ** [comment]
Let's take a look at this and check if it's still relevant.

**Comment by JJ** [comment]
I don't think the problem is `prove`, the problem might be if `tput` is installed or not on the system. What I'm going to do is to check that during installation
